### ISSUE TITLE
Pre-Release

### ISSUE THREAD

**Issue by Draculente** [hoppjan/LuebeckMensaWidget#17]
As I uninstalled the working version yesterday for testing purposes, I would love to have a pre-release with a working apk that I can reinstall without having to build it manually.

**Comment by hoppjan** [comment]
Tried, failed. 😢 
Where did I go wrong? @Importantus

**Comment by Importantus** [comment]
The error occurs when attempting to create or update a release tag in GitHub Actions, indicating that the integration account does not have the necessary access rights to create or update tags in the repository. Check the access control settings in the repository and verify that the account executing the actions has the appropriate permissions for creating tags.

**Comment by Importantus** [comment]
Now it worked! What was the reason? And why is the release only a draft?
